name: Install R Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-r-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2" # Specify R version

      # Step 3: Install R package
      - name: Install R Package
        run: |
          R -e "devtools::install_deps(dep = TRUE)"
          R CMD build .
