# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: rocker/tidyverse
    name: isntall and test 
    
    steps:
      - uses: actions/checkout@v4

      # - name: install lib dependency
      #   run: apt install libglpk-dev

      - name: install pak
        run: R -e 'install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'
        
      - name: install dependencies
        run: |
          R -e "library(pak); pak::local_install_deps()"

      - name: runs test
        run: |
          R -e "library(devtools); test('.')"

